config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  get 'admin/tournament_teams'
  scope module: :user do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get 'users/unsubscribe'
    patch 'users/withdraw' => 'users#withdraw', as: 'users/withdraw'
    get 'games/:id/alps_first' => 'supports#alps_first', as: 'alps_first/support'
    get 'games/:id/alps_third' => 'supports#alps_third', as: 'alps_third/support'
    get 'games/:id/stand' => 'supports#stand', as: 'stand/support'
    resources :games, only: [:index, :show]
    resources :tournaments, only: [:index, :show]
    resources :supports, only: [:index, :create] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
  end
  namespace :admin do
    root to: "homes#top"
    resources :tournaments, only: [:new, :create, :index, :edit, :update, :show, :destroy]
    resources :teams, only: [:create, :index, :show, :edit, :update]
    resources :games, only: [:create, :index, :show, :edit, :update]
    resources :users, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/support.rb
class Support < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_one_attached :icon
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, uniqueness: true
         
  has_one_attached :icon
  has_many :supports, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_icon(width, height)
  unless icon.attached?
    file_path = Rails.root.join('app/assets/images/ball.png')
    icon.attach(io: File.open(file_path), filename: 'default-icon.png', content_type: 'image/png')
  end
  icon.variant(resize_to_limit: [width, height]).processed
  end
  
 def active_for_authentication?
    super && (is_deleted == false)
 end
 
 def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
 end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    support = Support.find(params[:support_id])
    favorite = current_user.favorites.new(support_id: support.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    support = Support.find(params[:support_id])
    favorite = current_user.favorites.find_by(support_id: support.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/user/games_controller.rb
class User::GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/supports_controller.rb
class User::SupportsController < ApplicationController
  def index
  end

  def alps_first
    @game = Game.find(params[:id])
    @support = Support.new
    @supports = Support.where.not(alps_first: "").order(id: "DESC").limit(20)
  end

  def alps_third
    @game = Game.find(params[:id])
    @support = Support.new
    @supports = Support.where.not(alps_third: "").order(id: "DESC").limit(20)
  end

  def stand
    @game = Game.find(params[:id])
    @support = Support.new
    @supports = Support.where.not(stand: "").order(id: "DESC").limit(20)
  end

  def create
    @support = Support.new(support_params)
    @support.user_id = current_user.id
    @support.save!
    redirect_back(fallback_location: root_path)
  end

  private
  def support_params
    params.require(:support).permit(:game_id, :alps_first, :alps_third, :stand)
  end
end

app/controllers/user/tournaments_controller.rb
class User::TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all
  end

  def show
    @tournament = Tournament.find(params[:id])
    @teams = @tournament.teams
    @games = @tournament.games
  end
  
  private
  def tournament_params
    params.require(:tournament).permit(:tytle, :short_tytle)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :icon, :email)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to post_images_path
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
  protected
  def user_state
    @user = User.find_by(email: params[:user][:email])
    if @user
     if @user.valid_password?(params[:user][:password]) && (!@user.is_deleted == false)
      redirect_to new_user_registration_path
     end
    end
  end
  
  def after_sign_in_path_for(resource)
    root_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/games_helper.rb
module User::GamesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/supports_helper.rb
module User::SupportsHelper
end

app/views/user/supports/alps_first.html.erb
<main>
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 mt-5">
              <h1><%= @game.game_teams[0].first_base ? @game.teams[0].team_name : @game.teams[1].team_name %>のアルプス</h1>
            </div>
            <div class="col-md-2">
                <%= link_to "スタンドへ", stand_support_path %>
            </div>
            <div class="col-md-2">
                <%= link_to "対戦相手のアルプスへ", alps_third_support_path %>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-12">
                <%= form_with model: @support do |f| %>
                <%= f.hidden_field :game_id, value: @game.id %>
                <h4>コメント</h4>
                <%= f.text_field :alps_first, class: "col-md-6" %>
                <%= f.hidden_field :alps_third, value: "" %>
                <%= f.hidden_field :stand, value: "" %>
                <%= f.submit '投稿' %>
                <% end %>
            </div>
        </div>
        <% @supports.each do |support| %>
        <div class="row mb-3">
            <div class="col-md-2, float-right">
                <%= image_tag support.user.get_icon(30,30) %>
            </div>
            <div class="col-md-8">
                <%= link_to user_path(support.user.id) do %>
                    <%= support.user.name %>
                <% end %></br>
                <%= support.alps_first %>
            </div>
            <div class="col-md-2">
                 <% if support.favorited_by?(current_user) %>
                    <p>
                      <%= link_to support_favorites_path(support), method: :delete do %>
                        ♥<%= support.favorites.count %> いいね
                      <% end %>
                    </p>
                      <% else %>
                    <p>
                      <%= link_to support_favorites_path(support), method: :post do %>
                        ♡<%= support.favorites.count %> いいね
                      <% end %>
                    </p>
                 <% end %>
            </div>
        </div>
        <% end %>
    </div>
</main>

app/views/user/supports/alps_third.html.erb
<main>
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 mt-5">
             <h1><%= @game.game_teams[1].first_base ? @game.teams[0].team_name : @game.teams[1].team_name %>のアルプス</h1>
            </div>
            <div class="col-md-2">
                <%= link_to "スタンドへ", stand_support_path %>
            </div>
            <div class="col-md-2">
                <%= link_to "対戦相手のアルプスへ", alps_first_support_path %>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-12">
                <%= form_with model: @support do |f| %>
                <%= f.hidden_field :game_id, value: @game.id %>
                <h4>コメント</h4>
                <%= f.text_field :alps_third, class: "col-md-6" %>
                <%= f.hidden_field :alps_first, value: "" %>
                <%= f.hidden_field :stand, value: "" %>
                <%= f.submit '投稿' %>
                <% end %>
            </div>
        </div>
        <% @supports.each do |support| %>
        <div class="row mb-3">
            <div class="col-md-2, float-right">
                <%= image_tag support.user.get_icon(30,30) %>
            </div>
            <div class="col-md-8">
                <%= link_to user_path(support.user.id) do %>
                    <%= support.user.name %>
                <% end %></br>
                <%= support.alps_third %>
            </div>
            <div class="col-md-2">
                 <% if support.favorited_by?(current_user) %>
                    <p>
                      <%= link_to support_favorites_path(support), method: :delete do %>
                        ♥<%= support.favorites.count %> いいね
                      <% end %>
                    </p>
                      <% else %>
                    <p>
                      <%= link_to support_favorites_path(support), method: :post do %>
                        ♡<%= support.favorites.count %> いいね
                      <% end %>
                    </p>
                 <% end %>
            </div>
        </div>
        <% end %>
    </div>
</main>

app/views/user/supports/index.html.erb
<h1>User::Supports#index</h1>
<p>Find me in app/views/user/supports/index.html.erb</p>

app/views/user/supports/stand.html.erb
<main>
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 mt-5">
             <h1>スタンド</h1>
            </div>
            <div class="col-md-2">
                <%= link_to "一塁側のアルプスへ", alps_first_support_path %>
            </div>
            <div class="col-md-2">
                <%= link_to "三塁側のアルプスへ", alps_third_support_path %>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-12">
                <%= form_with model: @support do |f| %>
                <%= f.hidden_field :game_id, value: @game.id %>
                <h4>コメント</h4>
                <%= f.text_field :stand, class: "col-md-6" %>
                <%= f.hidden_field :alps_first, value: "" %>
                <%= f.hidden_field :alps_third, value: "" %>
                <%= f.submit '投稿' %>
                <% end %>
            </div>
        </div>
        <% @supports.each do |support| %>
        <div class="row mb-3">
            <div class="col-md-2, float-right">
                <%= image_tag support.user.get_icon(30,30) %>
            </div>
            <div class="col-md-8">
                <%= link_to user_path(support.user.id) do %>
                    <%= support.user.name %>
                <% end %></br>
                <%= support.stand %>
            </div>
            <div class="col-md-2">
                 <% if support.favorited_by?(current_user) %>
                    <p>
                      <%= link_to support_favorites_path(support), method: :delete do %>
                        ♥<%= support.favorites.count %> いいね
                      <% end %>
                    </p>
                      <% else %>
                    <p>
                      <%= link_to support_favorites_path(support), method: :post do %>
                        ♡<%= support.favorites.count %> いいね
                      <% end %>
                    </p>
                 <% end %>
            </div>
        </div>
        <% end %>
    </div>
</main>